[tool.black]
line-length = 120
exclude = '''/(
  \.git
)/
'''

[tool.isort]
ensure_newline_before_comments = true
force_grid_wrap = 0
include_trailing_comma = true
indent = 4
line_length = 120
multi_line_output = 3
skip_gitignore = true
use_parentheses = true
