name: Get commit message

on:
  pull_request:
    type: [labeled]
    paths:
      - 'get_message/**'
      - '.github/workflow/**'

jobs:
  get-msg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set commit message to an environment variable
        run: |
          echo '::set-env name=message:: ${{ github.event.head_commit.message }}'
          echo $message
