name: stop-concurrency

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sum: [1, 2, 3, 4, 5]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test
        run: for i in `seq 1 ${{ matrix.sum }}`; do echo ${i}; sleep 1; done;
